export enum ENV {
  BOT_TOKEN = "BOT_TOKEN",
  GITHUB_API = "GITHUB_API",
  MEAL_API = "MEAL_API",
  SCHEDULE_API = "SCHEDULE_API",
  GUILD_ID = "GUILD_ID",
  CLIENT_ID = "CLIENT_ID",
  NODE_ENV = "NODE_ENV",
}
