name: Discord bot CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: create dotenv file
      run: |
        touch ./discord/.env
        echo "${{ secrets.DATA }}" >> ./discord/.env.production
  
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: badroom
        password: ${{ secrets.DOCKER_PW }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./discord
        push: true
        tags: badroom/anything:discord
    
    
    - name: docker run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo su
          docker stop discord
          docker rm discord
          docker rmi badroom/anything:discord
          docker pull badroom/anything:discord
          docker run -d --name discord badroom/anything:discord
