name: Discord bot CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: create dotenv file
      run: |
        touch ./discord/.env.production
        echo "${{ secrets.DOTENV }}" >> ./discord/.env.production
        ls ./discord
  
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: badroom
        password: ${{ secrets.DOCKER_PW }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        working-directory: ./discord
        context: ./discord
        push: true
        tags: badroom/anything:discord
        
    
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
#       - name: Login to ghcr
#         uses: docker/login-action@v2.0.0
#         with:
#           username: badroom
#           password: ${{ secrets.DOCKER_PW }}

      - name: Docker run
        run: |
          sudo docker stop discord
          sudo docker rm discord
          sudo docker rmi badroom/anything:discord
          sudo docker run -d --name discord badroom/anything:discord
