name: Discord bot CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'discord/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: ./discord/yarn.lock
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      
    - run: yarn install --frozen-lockfile
      working-directory: ./discord
      
    - run: yarn build
      working-directory: ./discord
